version: '3'

services:
  app:
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: gunicorn -w 1 -b :8000 app:server


  api_server:
    restart: always
    build: ./flask_api
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: gunicorn -w 1 -b :5000 app:app


  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - api_server
