version: '2'

services:
  app:
    restart: always
    build: ./www
    expose:
      - "8000"
    volumes:
      - /home/project/www/static
    command: gunicorn -w 2 -b :8000 app:server

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - app
    depends_on:
      - app